### ISSUE TITLE
树莓派下安装报错

### ISSUE THREAD

**Issue by linxingyulxy** [Baidu-AIP/python-sdk#3]
hassbian 系统 ，python 2.7.13，报错如下
`pi@hassbian:~ $ sudo pip install --proxy=127.0.0.1:8124 git+https://github.com/Baidu-AIP/python-sdk.git@master
Collecting git+https://github.com/Baidu-AIP/python-sdk.git@master
  Cloning https://github.com/Baidu-AIP/python-sdk.git (to master) to /tmp/pip-ov14NS-build
Collecting Pillow (from baidu-aip==1.6.9.0)
  Using cached Pillow-4.3.0.tar.gz
Requirement already satisfied: requests in /usr/local/lib/python2.7/dist-packages (from baidu-aip==1.6.9.0)
Requirement already satisfied: olefile in /usr/local/lib/python2.7/dist-packages (from Pillow->baidu-aip==1.6.9.0)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests->baidu-aip==1.6.9.0)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests->baidu-aip==1.6.9.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests->baidu-aip==1.6.9.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests->baidu-aip==1.6.9.0)
Building wheels for collected packages: Pillow
  Running setup.py bdist_wheel for Pillow ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-3Z0mrC/Pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpC5s4Rypip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-armv7l-2.7
  creating build/lib.linux-armv7l-2.7/PIL
  copying PIL/DcxImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/_binary.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/GbrImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageOps.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PyAccess.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/JpegImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/XVThumbImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/FtexImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ExifTags.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/WalImageFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageDraw2.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/TiffImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageFilter.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageCms.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageChops.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PdfImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PalmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageTk.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/BmpImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PpmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImtImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/IptcImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageQt.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/WebPImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageSequence.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/FitsStubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PcfFontFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/_tkinter_finder.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/SpiderImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PsdImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/MspImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/GifImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/features.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/TiffTags.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PSDraw.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/WmfImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImagePalette.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageGrab.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageEnhance.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/XpmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/FpxImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/GimpGradientFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/BdfFontFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/_util.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImagePath.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/GdImageFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/XbmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageShow.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/MicImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/OleFileIO.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/__init__.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/McIdasImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageWin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/MpoImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageTransform.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/IcoImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/SgiImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageStat.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/TarIO.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/EpsImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/GimpPaletteFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageMode.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/BufrStubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/DdsImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageMath.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/FontFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PcdImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageFont.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/SunImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/CurImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/FliImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/JpegPresets.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageDraw.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ContainerIO.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/TgaImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/Image.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/Jpeg2KImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PaletteFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/IcnsImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/MpegImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/Hdf5StubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/version.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageMorph.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/GribStubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PcxImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PixarImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageColor.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PngImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  running egg_info
  writing requirements to Pillow.egg-info/requires.txt
  writing Pillow.egg-info/PKG-INFO
  writing top-level names to Pillow.egg-info/top_level.txt
  writing dependency_links to Pillow.egg-info/dependency_links.txt
  reading manifest file 'Pillow.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.sh'
  no previously-included directories found matching 'docs/_static'
  warning: no previously-included files found matching '.coveragerc'
  warning: no previously-included files found matching 'codecov.yml'
  warning: no previously-included files found matching '.editorconfig'
  warning: no previously-included files found matching '.landscape.yaml'
  warning: no previously-included files found matching '.travis'
  warning: no previously-included files found matching '.travis/*'
  warning: no previously-included files found matching 'appveyor.yml'
  warning: no previously-included files found matching 'build_children.sh'
  warning: no previously-included files found matching 'tox.ini'
  warning: no previously-included files matching '.git*' found anywhere in distribution
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.so' found anywhere in distribution
  writing manifest file 'Pillow.egg-info/SOURCES.txt'
  running build_ext
  
  
  The headers or library files could not be found for jpeg,
  a required dependency when compiling Pillow from source.
  
  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-3Z0mrC/Pillow/setup.py", line 799, in <module>
      raise RequiredDependencyException(msg)
  __main__.RequiredDependencyException:
  
  The headers or library files could not be found for jpeg,
  a required dependency when compiling Pillow from source.
  
  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html
  
  
  
  ----------------------------------------
  Failed building wheel for Pillow
  Running setup.py clean for Pillow
Failed to build Pillow
Installing collected packages: Pillow, baidu-aip
  Running setup.py install for Pillow ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-3Z0mrC/Pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-AXVGAY-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-armv7l-2.7
    creating build/lib.linux-armv7l-2.7/PIL
    copying PIL/DcxImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/_binary.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/GbrImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageOps.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/PyAccess.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/JpegImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/XVThumbImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/FtexImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ExifTags.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/WalImageFile.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageDraw2.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/TiffImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageFilter.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageCms.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageChops.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/PdfImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/PalmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageTk.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/BmpImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/PpmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImtImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/IptcImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageQt.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/WebPImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageSequence.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/FitsStubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/PcfFontFile.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/_tkinter_finder.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/SpiderImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/PsdImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/MspImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/GifImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/features.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/TiffTags.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/PSDraw.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/WmfImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImagePalette.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageGrab.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageFile.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageEnhance.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/XpmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/FpxImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/GimpGradientFile.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/BdfFontFile.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/_util.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImagePath.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/GdImageFile.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/XbmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageShow.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/MicImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/OleFileIO.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/__init__.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/McIdasImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageWin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/MpoImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageTransform.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/IcoImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/SgiImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageStat.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/TarIO.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/EpsImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/GimpPaletteFile.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageMode.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/BufrStubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/DdsImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageMath.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/FontFile.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/PcdImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageFont.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/SunImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/CurImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/FliImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/JpegPresets.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageDraw.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ContainerIO.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/TgaImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/Image.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/Jpeg2KImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/PaletteFile.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/IcnsImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/MpegImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/Hdf5StubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/version.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageMorph.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/GribStubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/PcxImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/PixarImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageColor.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/PngImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    running egg_info
    writing requirements to Pillow.egg-info/requires.txt
    writing Pillow.egg-info/PKG-INFO
    writing top-level names to Pillow.egg-info/top_level.txt
    writing dependency_links to Pillow.egg-info/dependency_links.txt
    reading manifest file 'Pillow.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.sh'
    no previously-included directories found matching 'docs/_static'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching 'codecov.yml'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.landscape.yaml'
    warning: no previously-included files found matching '.travis'
    warning: no previously-included files found matching '.travis/*'
    warning: no previously-included files found matching 'appveyor.yml'
    warning: no previously-included files found matching 'build_children.sh'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    writing manifest file 'Pillow.egg-info/SOURCES.txt'
    running build_ext
    
    
    The headers or library files could not be found for jpeg,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-3Z0mrC/Pillow/setup.py", line 799, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException:
    
    The headers or library files could not be found for jpeg,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-3Z0mrC/Pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-AXVGAY-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-3Z0mrC/Pillow/`

**Comment by linxingyulxy** [comment]
帮忙看下 这是为什么

**Comment by iMuduo** [comment]
pillow无法安装导致，请使用最新版本，已经移除pillow依赖
