### ISSUE TITLE
不支持python3.5吗？

### ISSUE THREAD

**Issue by mountainguan** [Baidu-AIP/python-sdk#5]
File "/usr/local/lib/python3.5/dist-packages/aip/__init__.py", line 6, in <module>
    from ocr import AipOcr
ImportError: No module named 'ocr'

**Comment by iMuduo** [comment]
你用的哪个库？pip install baidu-aip —upgrade


原始邮件
发件人:mountainguannotifications@github.com
收件人:Baidu-AIP/python-sdkpython-sdk@noreply.github.com
抄送:Subscribedsubscribed@noreply.github.com
发送时间:2018年5月28日(周一) 10:55
主题:[Baidu-AIP/python-sdk] 不支持python3.5吗？ (#5)


File "/usr/local/lib/python3.5/dist-packages/aip/init.py", line 6, in 
 from ocr import AipOcr
 ImportError: No module named 'ocr'

**Comment by mountainguan** [comment]
更新以后又可以了，可能是包损坏了
